[toolchain]
# Use the stable channel
channel = "stable"

# Specify target platforms for cross-compilation
# Only enable these if you need cross-compilation
# targets = [
#    "x86_64-unknown-linux-gnu",
#    "x86_64-pc-windows-msvc",
#    "x86_64-apple-darwin",
#    "aarch64-apple-darwin"
#    # universal-apple-darwin is a special target that combines both macOS architectures
#    # and is handled specially by the build system
# ]

# Install only the components we need to minimize installation time
components = ["rustc", "cargo", "rust-std"]

# Make sure toolchain installation works even with intermittent network issues
profile = "minimal"
