# This file contains Cargo configuration to optimize Rust build times
# both locally and in CI environments

[build]
# Compile with parallel jobs by default
jobs = 4

# Enable cross-compilation if needed
# target = ["x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc", "x86_64-apple-darwin", "aarch64-apple-darwin"]

# Configuration for macOS universal builds
[target.universal-apple-darwin]
# This is not a real rustc target, but a special target used by Tauri for universal macOS builds
# When building for this target, both x86_64-apple-darwin and aarch64-apple-darwin will be built
# and combined into a universal binary

[profile.dev]
# Optimize for faster development builds
opt-level = 1
debug = 0
split-debuginfo = "unpacked"
incremental = true

[profile.release]
# Optimize for size and speed in release builds
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "abort"
strip = true

[net]
# Improve network reliability
retry = 10
git-fetch-with-cli = true

[term]
# Always use color output
color = "always"

[cargo-new]
# Set defaults for new projects
vcs = "git"
