name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, windows-latest, ubuntu-latest]
        dotnet: ['9.0.x']

    runs-on: ${{ matrix.platform }}
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        
      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          # Try to determine the correct WebKitGTK package name for current Ubuntu version
          if apt-cache show libwebkit2gtk-4.0-dev > /dev/null 2>&1; then
            WEBKIT_DEV_PACKAGE="libwebkit2gtk-4.0-dev"
          elif apt-cache show libwebkit2gtk-4.1-dev > /dev/null 2>&1; then
            # Ubuntu 24.04 (Noble) uses WebKitGTK 4.1
            WEBKIT_DEV_PACKAGE="libwebkit2gtk-4.1-dev"
          elif apt-cache show libwebkit2gtk-6.0-dev > /dev/null 2>&1; then
            # Future Ubuntu versions might use WebKitGTK 6.0
            WEBKIT_DEV_PACKAGE="libwebkit2gtk-6.0-dev"
          else
            echo "Unable to determine WebKitGTK package name"
            exit 1
          fi
          echo "Using WebKitGTK package: $WEBKIT_DEV_PACKAGE"
          sudo apt-get install -y libgtk-3-dev $WEBKIT_DEV_PACKAGE libappindicator3-dev librsvg2-dev patchelf

      - name: Install Tauri CLI
        run: cargo install tauri-cli

      - name: Restore dependencies
        run: dotnet restore

      - name: Build Blazor WebAssembly App
        run: dotnet build -c Release --no-restore src/TauriBlazorBoilerplate.csproj

      - name: Run tests
        run: dotnet test --no-build --verbosity normal

      - name: Build Tauri Application
        run: cargo tauri build --ci
